CREATE DATABASE Patrimonio_Escolar

USE Patrimonio_Escolar;


CREATE TABLE Sala
(
	IdSala		    INT PRIMARY KEY IDENTITY,  -- INT NESSE CASO RETORNA UM NUMERO INTEIRO
	Andar			VARCHAR(200) NOT NULL,  -- CHAR USADOS PARA VALORES QUE NÃO IRÃO MUDAR
	Nome     		VARCHAR(200)NOT NULL,				-- VARCHAR USADO PARA TEXTOS QUE PODEM MUDAR
	Metragem    	VARCHAR(200) NOT NULL, 
);
GO


CREATE TABLE Equipamentos
(
	IdEquipamento		INT PRIMARY KEY IDENTITY,  
	IdSala			    INT FOREIGN KEY REFERENCES Sala(IdSala),
	Marca				VARCHAR(200)NOT NULL,				
	Tipo				VARCHAR(200)NOT NULL, 
	Numero_de_Serie		CHAR(200)NOT NULL,
	Descricao			VARCHAR(200)NOT NULL,
	Status_             VARCHAR(200)NOT NULL        

);
GO

CREATE TABLE Usuario 
(
	IdUsuario INT PRIMARY KEY IDENTITY,
	Email    VARCHAR(200)NOT NULL,
	Senha    VARCHAR(200)NOT NULL

);
